project_name: slackdice

port: 9019
python: python2
type: flask

# Configs below will not usually change
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
deploy_dir: "{{ install_root }}/{{ project_name }}"
application_dir: "{{ deploy_dir }}"
requirements_file: "{{ deploy_dir }}/requirements.txt"
service_name: "apps/{{ project_name }}"
virtualenv: "{{ virtualenv_root }}/{{ project_name }}"
wsgi_application: "wsgi:application"
env_setup_script: "{{ deploy_dir }}/env.sh"
env_run_script: "{{ deploy_dir }}/env_run.sh"

# Configs common to all projects
application_user: apps
install_root: /home/{{ application_user }}/sites
virtualenv_root: /home/{{ application_user }}/env
supported_envs:
  stg: master
  prd: stg
